### ISSUE TITLE
Osu Server List integration

### ISSUE THREAD

**Issue by marcandreher** [osuthailand/ragnarokapi#1]
For osu!ServerList I would need a route to check if a player exists and a stats route with players at least.

**Comment by simonglob** [comment]
added /api/v1/users/exists to the api. the server stats will be added into ragnarok, so the endpoint c.rina.place.

**Comment by simonglob** [comment]
ragnarok commit [3732f0e](https://github.com/osuthailand/Ragnarok/commit/3732f0ede0f5cf0b4e5419b89e2e9b20c14c6e73), changes https://c.rina.place to respond with server stats instead of title card.

so, the endpoints are:
api.rina.place/api/v1/users/exists?username=[username] 
^^^ responds with the id of the user. if the user wasn't found, it'll respond with an error.

c.rina.place/
^^^ responds with server uptime, online players and registered players.

**Comment by marcandreher** [comment]
api.rina.place/api/v1/users/exists?query=[username]
Requires a parameter query and parameter username why both or is this a bug?

**Comment by simonglob** [comment]
oh sorry, it's not ?query=, it's ?username=. my bad, i was thinking of the search endpoint @marcandreher 

i've edited the original message for other future references...
